apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp-container
        image: myapp:${GIT_COMMIT}  # Usa la imagen local creada en Minikube
        imagePullPolicy: Never  # No intenta extraer la imagen de un registro
        ports:
        - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  selector:
    app: myapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5001
      nodePort: 30001
  type: LoadBalancer